In [30]:
import nflreadpy as nfl

seasons = list(range(2016,2026))

player_stats = nfl.load_player_stats(
    seasons=seasons,
    summary_level="reg"
)

player_stats.head()

shape: (5, 143)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-000409 ┆ P.Dawson  ┆ Phil      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 1         ┆           ┆ Dawson    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001691 ┆ A.Vinatie ┆ Adam      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆ ri        ┆ Vinatieri ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001959 ┆ T.Brady   ┆ Tom Brady ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 258.56    ┆ 258.56    │
│ 6         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001964 ┆ S.Janikow ┆ Sebastian ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆ ski       ┆ Janikowsk ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ i         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001971 ┆ S.Lechler ┆ Shane     ┆ P        ┆ … ┆ 1         ┆ 2886      ┆ 0.0       ┆ 0.0       │
│ 4         ┆           ┆ Lechler   ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [31]:
print(player_stats.shape)
print(player_stats.columns)

(19531, 143)
['player_id', 'player_name', 'player_display_name', 'position', 'position_group', 'headshot_url', 'season', 'season_type', 'recent_team', 'games', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions', 'sacks_suffered', 'sack_yards_lost', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs', 'passing_epa', 'passing_cpoe', 'passing_2pt_conversions', 'pacr', 'passing_10', 'passing_16', 'passing_20', 'passing_40', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions', 'rushing_10', 'rushing_12', 'rushing_20', 'rushing_40', 'receptions', 'targets', 'receiving_yards', 'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions', 'receiving_10', 'receiving_16', 'receiving_20', 'receiving_40', 'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds', 'def_tackles_solo', 'def_tackles_with_assist', 'def_tackle_assists', 'def_tackles_for_loss', 'def_tackles_for_loss_yards', 'def_fumbles_forced', 'def_sacks', 'def_sack_yards', 'def_qb_hits', 'def_interceptions', 'def_interception_yards', 'def_pass_defended', 'def_tds', 'def_fumbles', 'def_safeties', 'misc_yards', 'fumble_recovery_own', 'fumble_recovery_yards_own', 'fumble_recovery_opp', 'fumble_recovery_yards_opp', 'fumble_recovery_tds', 'penalties', 'penalty_yards', 'fumbles_forced_by_opp', 'fumbles_not_forced', 'fumbles_out_of_bounds', 'fumbles_total', 'fumbles_lost_total', 'punt_returns', 'punt_return_yards', 'kickoff_returns', 'kickoff_return_yards', 'fg_made', 'fg_att', 'fg_missed', 'fg_blocked', 'fg_long', 'fg_pct', 'fg_made_0_19', 'fg_made_20_29', 'fg_made_30_39', 'fg_made_40_49', 'fg_made_50_59', 'fg_made_60_', 'fg_missed_0_19', 'fg_missed_20_29', 'fg_missed_30_39', 'fg_missed_40_49', 'fg_missed_50_59', 'fg_missed_60_', 'fg_made_list', 'fg_missed_list', 'fg_blocked_list', 'fg_made_distance', 'fg_missed_distance', 'fg_blocked_distance', 'pat_made', 'pat_att', 'pat_missed', 'pat_blocked', 'pat_pct', 'gwfg_made', 'gwfg_att', 'gwfg_missed', 'gwfg_blocked', 'gwfg_distance_list', 'pt_att', 'pt_blocked', 'pt_long', 'pt_yards', 'pt_inside_20', 'pt_out_of_bounds', 'pt_downed', 'pt_touchback', 'pt_fair_caught', 'pt_returned', 'pt_return_yards', 'pt_return_tds', 'pt_net_yards', 'fantasy_points', 'fantasy_points_ppr']

In [32]:
core_columns = [
    "player_id",
    "player_display_name",
    "position",
    "season",
    "recent_team",
    "games",

    # Passing
    "attempts",
    "passing_yards",
    "passing_tds",
    "passing_interceptions",
    "passing_2pt_conversions",

    # Rushing
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_2pt_conversions",

    # Receiving
    "targets",
    "receptions",
    "receiving_yards",
    "receiving_tds",
    "receiving_2pt_conversions",

    # Fumbles
    "fumbles_lost_total",
    "sack_fumbles_lost",
    "rushing_fumbles_lost",
    "receiving_fumbles_lost",

    # Special Teams
    "special_teams_tds",

    # Advanced Metrics
    "target_share",
    "air_yards_share",
    "wopr",

    # Existing Fantasy Points (For Comparison)
    "fantasy_points",
    "fantasy_points_ppr"
]

player_stats_core = player_stats.select(core_columns)

player_stats_core.head()

shape: (5, 30)
┌────────────┬─────────────┬──────────┬────────┬───┬─────────────┬──────┬─────────────┬────────────┐
│ player_id  ┆ player_disp ┆ position ┆ season ┆ … ┆ air_yards_s ┆ wopr ┆ fantasy_poi ┆ fantasy_po │
│ ---        ┆ lay_name    ┆ ---      ┆ ---    ┆   ┆ hare        ┆ ---  ┆ nts         ┆ ints_ppr   │
│ str        ┆ ---         ┆ str      ┆ i32    ┆   ┆ ---         ┆ f64  ┆ ---         ┆ ---        │
│            ┆ str         ┆          ┆        ┆   ┆ f64         ┆      ┆ f64         ┆ f64        │
╞════════════╪═════════════╪══════════╪════════╪═══╪═════════════╪══════╪═════════════╪════════════╡
│ 00-0004091 ┆ Phil Dawson ┆ K        ┆ 2016   ┆ … ┆ 0.0         ┆ 0.0  ┆ 0.0         ┆ 0.0        │
│ 00-0016919 ┆ Adam        ┆ K        ┆ 2016   ┆ … ┆ 0.0         ┆ 0.0  ┆ 0.0         ┆ 0.0        │
│            ┆ Vinatieri   ┆          ┆        ┆   ┆             ┆      ┆             ┆            │
│ 00-0019596 ┆ Tom Brady   ┆ QB       ┆ 2016   ┆ … ┆ 0.0         ┆ 0.0  ┆ 258.56      ┆ 258.56     │
│ 00-0019646 ┆ Sebastian   ┆ K        ┆ 2016   ┆ … ┆ 0.0         ┆ 0.0  ┆ 0.0         ┆ 0.0        │
│            ┆ Janikowski  ┆          ┆        ┆   ┆             ┆      ┆             ┆            │
│ 00-0019714 ┆ Shane       ┆ P        ┆ 2016   ┆ … ┆ 0.0         ┆ 0.0  ┆ 0.0         ┆ 0.0        │
│            ┆ Lechler     ┆          ┆        ┆   ┆             ┆      ┆             ┆            │
└────────────┴─────────────┴──────────┴────────┴───┴─────────────┴──────┴─────────────┴────────────┘

In [33]:
print(player_stats_core.shape)
print(player_stats_core.columns)

(19531, 30)
['player_id', 'player_display_name', 'position', 'season', 'recent_team', 'games', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions', 'passing_2pt_conversions', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_2pt_conversions', 'targets', 'receptions', 'receiving_yards', 'receiving_tds', 'receiving_2pt_conversions', 'fumbles_lost_total', 'sack_fumbles_lost', 'rushing_fumbles_lost', 'receiving_fumbles_lost', 'special_teams_tds', 'target_share', 'air_yards_share', 'wopr', 'fantasy_points', 'fantasy_points_ppr']

In [34]:
#Filter to only include QB, RB, WR, TE

fantasy_positions = ["QB","RB","WR","TE"]

player_stats_core = player_stats_core.filter(
    player_stats_core["position"].is_in(fantasy_positions)
)

player_stats_core.head()

shape: (5, 30)
┌────────────┬────────────┬──────────┬────────┬───┬────────────┬──────────┬────────────┬───────────┐
│ player_id  ┆ player_dis ┆ position ┆ season ┆ … ┆ air_yards_ ┆ wopr     ┆ fantasy_po ┆ fantasy_p │
│ ---        ┆ play_name  ┆ ---      ┆ ---    ┆   ┆ share      ┆ ---      ┆ ints       ┆ oints_ppr │
│ str        ┆ ---        ┆ str      ┆ i32    ┆   ┆ ---        ┆ f64      ┆ ---        ┆ ---       │
│            ┆ str        ┆          ┆        ┆   ┆ f64        ┆          ┆ f64        ┆ f64       │
╞════════════╪════════════╪══════════╪════════╪═══╪════════════╪══════════╪════════════╪═══════════╡
│ 00-0019596 ┆ Tom Brady  ┆ QB       ┆ 2016   ┆ … ┆ 0.0        ┆ 0.0      ┆ 258.56     ┆ 258.56    │
│ 00-0020337 ┆ Steve      ┆ WR       ┆ 2016   ┆ … ┆ 0.173146   ┆ 0.349021 ┆ 113.9      ┆ 183.9     │
│            ┆ Smith      ┆          ┆        ┆   ┆            ┆          ┆            ┆           │
│ 00-0020531 ┆ Drew Brees ┆ QB       ┆ 2016   ┆ … ┆ 0.0        ┆ 0.0      ┆ 332.32     ┆ 332.32    │
│ 00-0020679 ┆ Shaun Hill ┆ QB       ┆ 2016   ┆ … ┆ 0.0        ┆ 0.0      ┆ 10.18      ┆ 10.18     │
│ 00-0021206 ┆ Josh       ┆ QB       ┆ 2016   ┆ … ┆ 0.0        ┆ 0.0      ┆ 52.1       ┆ 52.1      │
│            ┆ McCown     ┆          ┆        ┆   ┆            ┆          ┆            ┆           │
└────────────┴────────────┴──────────┴────────┴───┴────────────┴──────────┴────────────┴───────────┘

In [35]:
#Checking to see how many players by position

player_stats_core.group_by("position").len().sort("position")

shape: (4, 2)
┌──────────┬──────┐
│ position ┆ len  │
│ ---      ┆ ---  │
│ str      ┆ u32  │
╞══════════╪══════╡
│ QB       ┆ 773  │
│ RB       ┆ 1516 │
│ TE       ┆ 1276 │
│ WR       ┆ 2309 │
└──────────┴──────┘

In [37]:
print(player_stats_core.shape)

player_stats_core.group_by("season").len().sort("season")

(5874, 30)

shape: (10, 2)
┌────────┬─────┐
│ season ┆ len │
│ ---    ┆ --- │
│ i32    ┆ u32 │
╞════════╪═════╡
│ 2016   ┆ 557 │
│ 2017   ┆ 553 │
│ 2018   ┆ 577 │
│ 2019   ┆ 572 │
│ 2020   ┆ 602 │
│ 2021   ┆ 633 │
│ 2022   ┆ 608 │
│ 2023   ┆ 576 │
│ 2024   ┆ 588 │
│ 2025   ┆ 608 │
└────────┴─────┘

In [38]:
#Checking for duplicate players 

duplicates = (
    player_stats_core
    .group_by(["player_id","season"])
    .len()
    .filter(player_stats_core.group_by(["player_id","season"]).len()["len"] > 1)
)

duplicates

shape: (0, 3)
┌───────────┬────────┬─────┐
│ player_id ┆ season ┆ len │
│ ---       ┆ ---    ┆ --- │
│ str       ┆ i32    ┆ u32 │
╞═══════════╪════════╪═════╡
└───────────┴────────┴─────┘

In [39]:
print("Duplicate player-seasons:", duplicates.height)

Duplicate player-seasons: 0

In [40]:
# Fantasy Score Self Calculation

import polars as pl

player_stats_core = player_stats_core.with_columns(
    (
        pl.col("passing_yards") / 25
        + pl.col("passing_tds") * 4
        - pl.col("passing_interceptions") * 2

        + pl.col("rushing_yards") / 10
        + pl.col("rushing_tds") * 6

        + pl.col("receiving_yards") / 10
        + pl.col("receptions")
        + pl.col("receiving_tds") * 6

        + pl.col("passing_2pt_conversions") * 2
        + pl.col("rushing_2pt_conversions") * 2
        + pl.col("receiving_2pt_conversions") * 2

        + pl.col("special_teams_tds") * 6

        - (
            pl.col("sack_fumbles_lost")
            + pl.col("rushing_fumbles_lost")
            + pl.col("receiving_fumbles_lost")
        ) * 2

    ).alias("calculated_fantasy_points_ppr")
)

In [41]:
#Comparing self calculated score with actual fantasy points

comparison = player_stats_core.select([
    "player_display_name",
    "position",
    "fantasy_points_ppr",
    "calculated_fantasy_points_ppr"
]).with_columns(
    (
        pl.col("calculated_fantasy_points_ppr")
        - pl.col("fantasy_points_ppr")
    ).alias("difference")
)

comparison.sort(
    pl.col("difference").abs(),
    descending=True
).head(20)

shape: (20, 5)
┌─────────────────────┬──────────┬────────────────────┬──────────────────────────────┬─────────────┐
│ player_display_name ┆ position ┆ fantasy_points_ppr ┆ calculated_fantasy_points_pp ┆ difference  │
│ ---                 ┆ ---      ┆ ---                ┆ r                            ┆ ---         │
│ str                 ┆ str      ┆ f64                ┆ ---                          ┆ f64         │
│                     ┆          ┆                    ┆ f64                          ┆             │
╞═════════════════════╪══════════╪════════════════════╪══════════════════════════════╪═════════════╡
│ LeSean McCoy        ┆ RB       ┆ 298.3              ┆ 298.3                        ┆ -5.6843e-14 │
│ Russell Wilson      ┆ QB       ┆ 270.06             ┆ 270.06                       ┆ -5.6843e-14 │
│ Ezekiel Elliott     ┆ RB       ┆ 325.4              ┆ 325.4                        ┆ 5.6843e-14  │
│ Deshaun Watson      ┆ QB       ┆ 320.98             ┆ 320.98                       ┆ 5.6843e-14  │
│ Aaron Rodgers       ┆ QB       ┆ 383.26             ┆ 383.26                       ┆ -5.6843e-14 │
│ …                   ┆ …        ┆ …                  ┆ …                            ┆ …           │
│ Sam Howell          ┆ QB       ┆ 257.54             ┆ 257.54                       ┆ -5.6843e-14 │
│ Derrick Henry       ┆ RB       ┆ 336.4              ┆ 336.4                        ┆ 5.6843e-14  │
│ James Cook          ┆ RB       ┆ 266.7              ┆ 266.7                        ┆ 5.6843e-14  │
│ Bijan Robinson      ┆ RB       ┆ 341.7              ┆ 341.7                        ┆ -5.6843e-14 │
│ Jahmyr Gibbs        ┆ RB       ┆ 362.9              ┆ 362.9                        ┆ 5.6843e-14  │
└─────────────────────┴──────────┴────────────────────┴──────────────────────────────┴─────────────┘

In [42]:
comparison.select(
    pl.col("difference").abs().mean().alias("mean_absolute_difference"),
    pl.col("difference").abs().max().alias("max_absolute_difference")
)

shape: (1, 2)
┌──────────────────────────┬─────────────────────────┐
│ mean_absolute_difference ┆ max_absolute_difference │
│ ---                      ┆ ---                     │
│ f64                      ┆ f64                     │
╞══════════════════════════╪═════════════════════════╡
│ 1.0445e-15               ┆ 5.6843e-14              │
└──────────────────────────┴─────────────────────────┘

In [43]:
comparison.filter(
    pl.col("difference") != 0
).sort(
    pl.col("difference").abs(),
    descending=True
)

shape: (384, 5)
┌──────────────────────┬──────────┬────────────────────┬─────────────────────────────┬─────────────┐
│ player_display_name  ┆ position ┆ fantasy_points_ppr ┆ calculated_fantasy_points_p ┆ difference  │
│ ---                  ┆ ---      ┆ ---                ┆ pr                          ┆ ---         │
│ str                  ┆ str      ┆ f64                ┆ ---                         ┆ f64         │
│                      ┆          ┆                    ┆ f64                         ┆             │
╞══════════════════════╪══════════╪════════════════════╪═════════════════════════════╪═════════════╡
│ LeSean McCoy         ┆ RB       ┆ 298.3              ┆ 298.3                       ┆ -5.6843e-14 │
│ Russell Wilson       ┆ QB       ┆ 270.06             ┆ 270.06                      ┆ -5.6843e-14 │
│ Ezekiel Elliott      ┆ RB       ┆ 325.4              ┆ 325.4                       ┆ 5.6843e-14  │
│ Deshaun Watson       ┆ QB       ┆ 320.98             ┆ 320.98                      ┆ 5.6843e-14  │
│ Aaron Rodgers        ┆ QB       ┆ 383.26             ┆ 383.26                      ┆ -5.6843e-14 │
│ …                    ┆ …        ┆ …                  ┆ …                           ┆ …           │
│ Adrian Killins Jr.   ┆ RB       ┆ 0.0                ┆ -2.2204e-16                 ┆ -2.2204e-16 │
│ Racey McMath         ┆ WR       ┆ 0.8                ┆ 0.8                         ┆ -2.2204e-16 │
│ Ihmir Smith-Marsette ┆ WR       ┆ 0.4                ┆ 0.4                         ┆ -2.2204e-16 │
│ Chris Collier        ┆ RB       ┆ 1.8                ┆ 1.8                         ┆ 2.2204e-16  │
│ Cody Schrader        ┆ RB       ┆ 1.9                ┆ 1.9                         ┆ 2.2204e-16  │
└──────────────────────┴──────────┴────────────────────┴─────────────────────────────┴─────────────┘

In [44]:
problem_players = (
    comparison
    .filter(pl.col("difference") != 0)
    .select("player_display_name")
)

player_stats_core.join(
    problem_players,
    on="player_display_name",
    how="inner"
).select([
    "player_display_name",
    "position",
    "passing_2pt_conversions",
    "rushing_2pt_conversions",
    "receiving_2pt_conversions",
    "special_teams_tds",
    "fumbles_lost_total",
    "fantasy_points_ppr",
    "calculated_fantasy_points_ppr"
])

shape: (1_981, 9)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_di ┆ position ┆ passing_2 ┆ rushing_2 ┆ … ┆ special_t ┆ fumbles_l ┆ fantasy_p ┆ calculate │
│ splay_nam ┆ ---      ┆ pt_conver ┆ pt_conver ┆   ┆ eams_tds  ┆ ost_total ┆ oints_ppr ┆ d_fantasy │
│ e         ┆ str      ┆ sions     ┆ sions     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ _points_p │
│ ---       ┆          ┆ ---       ┆ ---       ┆   ┆ i32       ┆ i32       ┆ f64       ┆ pr        │
│ str       ┆          ┆ i32       ┆ i32       ┆   ┆           ┆           ┆           ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Alex      ┆ QB       ┆ 2         ┆ 0         ┆ … ┆ 0         ┆ 4         ┆ 224.78    ┆ 224.78    │
│ Smith     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Aaron     ┆ QB       ┆ 1         ┆ 1         ┆ … ┆ 0         ┆ 4         ┆ 380.02    ┆ 380.02    │
│ Rodgers   ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Aaron     ┆ QB       ┆ 1         ┆ 1         ┆ … ┆ 0         ┆ 4         ┆ 380.02    ┆ 380.02    │
│ Rodgers   ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Frank     ┆ RB       ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 1         ┆ 214.2     ┆ 214.2     │
│ Gore      ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Darren    ┆ RB       ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 162.5     ┆ 162.5     │
│ Sproles   ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Woody     ┆ RB       ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 145.1     ┆ 145.1     │
│ Marks     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Cam       ┆ RB       ┆ 0         ┆ 1         ┆ … ┆ 0         ┆ 1         ┆ 127.7     ┆ 127.7     │
│ Skattebo  ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ Bhayshul  ┆ RB       ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 1         ┆ 88.6      ┆ 88.6      │
│ Tuten     ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ RJ Harvey ┆ RB       ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 1         ┆ 206.6     ┆ 206.6     │
│ TreVeyon  ┆ RB       ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 1         ┆ 206.2     ┆ 206.2     │
│ Henderson ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [45]:
player_stats_core.write_csv("../data/raw/player_stats_2016_2025.csv")

In [46]:
import os

os.path.exists("../data/raw/player_stats_2016_2025.csv")

True